import { PRIMITIVES } from "@flarecraft/catalog";
import {
  incoming,
  outgoing,
  planDeployment,
  type Edge,
  type Node,
  type SystemModel,
} from "@flarecraft/model";

/**
 * The system, written down.
 *
 * flarecraft designs topology and never writes business logic, which leaves a
 * handoff: somebody — a person or a coding agent — has to turn the shape into
 * an application. A wrangler config is a poor brief for that. It says a Worker
 * holds `env.ORDERS`; it does not say what the Worker is for, what reaches it,
 * or what still has to be built.
 *
 * So this is generated to be read by whoever implements it. Every claim in it
 * is derived from the model, which means it cannot drift from the configs
 * sitting beside it — it is regenerated whenever the canvas changes.
 */

const label = (node: Node): string => PRIMITIVES[node.kind]?.label ?? node.kind;

const nameOf = (system: SystemModel, id: string): string =>
  system.nodes.find((n) => n.id === id)?.name ?? id;

/** How an edge actually moves data, in words rather than a binding type. */
function mechanism(edge: Edge, system: SystemModel): string {
  const to = system.nodes.find((n) => n.id === edge.to);
  switch (edge.kind) {
    case "service":
      return edge.entrypoint
        ? `calls it directly over RPC (\`${edge.entrypoint}\`), and waits for the reply`
        : "calls it directly and waits for the reply";
    case "queue_consumer":
      return "delivers messages to it in batches, asynchronously";
    case "trigger":
      return "causes it to run";
    case "tail":
      return "streams its logs there";
    default:
      return `reads and writes it as \`env.${edge.bindingName}\`${
        to ? ` (${label(to)})` : ""
      }`;
  }
}

/** What is left to build in a Worker, read off the edges attached to it. */
function todo(system: SystemModel, worker: Node): string[] {
  const inbound = incoming(system, worker.id);
  const items: string[] = [];

  const triggers = inbound.filter((e) => e.kind === "trigger");
  const crons = triggers.filter(
    (e) => system.nodes.find((n) => n.id === e.from)?.kind === "cron",
  );
  const routes = triggers.filter((e) =>
    ["route", "custom_domain"].includes(
      system.nodes.find((n) => n.id === e.from)?.kind ?? "",
    ),
  );
  const queues = inbound.filter((e) => e.kind === "queue_consumer");
  const services = inbound.filter((e) => e.kind === "service");

  if (routes.length > 0 || (crons.length === 0 && queues.length === 0)) {
    items.push(
      `\`fetch\` handler${
        routes.length > 0
          ? ` — serves ${routes.map((e) => `\`${nameOf(system, e.from)}\``).join(", ")}`
          : ""
      }`,
    );
  }
  for (const cron of crons) {
    items.push(
      `\`scheduled\` handler — runs on \`${nameOf(system, cron.from)}\`. Nothing prevents overlapping runs, so guard anything that must not run twice at once`,
    );
  }
  for (const queue of queues) {
    const batch = queue.consumer?.maxBatchSize ?? 10;
    const dlq = queue.consumer?.deadLetterQueue;
    items.push(
      `\`queue\` handler — up to ${batch} messages per batch from \`${nameOf(system, queue.from)}\`. ${
        dlq
          ? `Failures land in \`${dlq}\` after retries.`
          : "There is no dead-letter queue, so a message that fails every retry is dropped silently."
      }`,
    );
  }
  if (services.length > 0) {
    items.push(
      `RPC surface for ${services
        .map((e) => `\`${nameOf(system, e.from)}\``)
        .join(", ")}, which call into this Worker`,
    );
  }

  return items;
}

export function emitBlueprint(system: SystemModel): string {
  const workers = system.nodes.filter((n) => n.kind === "worker");
  const lines: string[] = [];

  lines.push(`# ${system.name}`, "");
  lines.push(
    "Generated by flarecraft from the topology. Regenerated whenever the canvas",
    "changes, so it cannot drift from the configs beside it — edit the design,",
    "not this file.",
    "",
  );

  // --- Shape -------------------------------------------------------------
  const counts = new Map<string, number>();
  for (const node of system.nodes) {
    const key = label(node);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }

  lines.push("## What this is", "");
  lines.push(
    `${workers.length} Worker${workers.length === 1 ? "" : "s"} and ${
      system.nodes.length - workers.length
    } other element${system.nodes.length - workers.length === 1 ? "" : "s"}, wired with ${
      system.edges.length
    } connection${system.edges.length === 1 ? "" : "s"}.`,
    "",
  );
  for (const [kind, count] of [...counts].sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${count} × ${kind}`);
  }
  lines.push("");

  // --- Entry points ------------------------------------------------------
  const ingress = system.nodes.filter(
    (n) => PRIMITIVES[n.kind]?.category === "ingress",
  );
  lines.push("## How work enters", "");
  if (ingress.length === 0) {
    lines.push(
      "Nothing triggers this system yet. Until a route, cron, or queue points at",
      "a Worker, none of it will ever run.",
      "",
    );
  } else {
    for (const entry of ingress) {
      for (const edge of outgoing(system, entry.id)) {
        lines.push(
          `- **${entry.name}** (${label(entry)}) → \`${nameOf(system, edge.to)}\``,
        );
      }
    }
    lines.push("");
  }

  // --- Per-element -------------------------------------------------------
  lines.push("## The elements", "");
  for (const worker of workers) {
    lines.push(`### ${worker.name}`, "");

    const config = worker.worker;
    const facts: string[] = [];
    if (config?.compatibilityDate) {
      facts.push(`compatibility date \`${config.compatibilityDate}\``);
    }
    if (config?.compatibilityFlags?.length) {
      facts.push(`flags \`${config.compatibilityFlags.join("`, `")}\``);
    }
    if (config?.observability?.enabled) facts.push("observability on");
    if (facts.length > 0) lines.push(facts.join(" · "), "");

    const inbound = incoming(system, worker.id);
    if (inbound.length > 0) {
      lines.push("Reached by:", "");
      for (const edge of inbound) {
        lines.push(
          `- \`${nameOf(system, edge.from)}\` ${mechanism(edge, system)}`,
        );
      }
      lines.push("");
    }

    const out = outgoing(system, worker.id);
    if (out.length > 0) {
      lines.push("Has access to:", "");
      for (const edge of out) {
        const target = system.nodes.find((n) => n.id === edge.to);
        lines.push(
          `- **${target?.name ?? edge.to}** — ${mechanism(edge, system)}`,
        );
      }
      lines.push("");
    }

    const work = todo(system, worker);
    if (work.length > 0) {
      lines.push("To implement:", "");
      for (const item of work) lines.push(`- ${item}`);
      lines.push("");
    }
  }

  // Non-Worker elements get a short entry: what they are and who uses them.
  const others = system.nodes.filter(
    (n) => n.kind !== "worker" && PRIMITIVES[n.kind]?.category !== "ingress",
  );
  if (others.length > 0) {
    lines.push("### Resources", "");
    for (const node of others) {
      const users = incoming(system, node.id)
        .map((e) => `\`${nameOf(system, e.from)}\``)
        .join(", ");
      lines.push(
        `- **${node.name}** (${label(node)}) — ${
          PRIMITIVES[node.kind]?.summary ?? ""
        }${users ? ` Used by ${users}.` : " Nothing binds it yet."}`,
      );
    }
    lines.push("");
  }

  // --- Communication -----------------------------------------------------
  lines.push("## Data flow", "");
  if (system.edges.length === 0) {
    lines.push("Nothing is connected yet.", "");
  } else {
    lines.push("| From | To | How | Binding |", "|---|---|---|---|");
    for (const edge of system.edges) {
      lines.push(
        `| ${nameOf(system, edge.from)} | ${nameOf(system, edge.to)} | ${
          edge.kind === "binding" ? "binding" : edge.kind.replace("_", " ")
        } | ${edge.bindingName ? `\`env.${edge.bindingName}\`` : "—"} |`,
      );
    }
    lines.push("");
  }

  // --- Deploy ------------------------------------------------------------
  const plan = planDeployment(system);
  lines.push("## Getting it running", "");
  if (plan.blockers.length > 0) {
    lines.push("Blocked:", "");
    for (const blocker of plan.blockers) lines.push(`- ${blocker}`);
    lines.push("");
  }
  if (plan.steps.length > 0) {
    lines.push("In this order:", "");
    plan.steps.forEach((step, index) => {
      lines.push(`${index + 1}. \`${step.command}\` — ${step.why}`);
    });
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "Anything not listed under *To implement* is already handled by the",
    "generated configs. The handlers are yours to write; flarecraft will not",
    "touch them again.",
    "",
  );

  return lines.join("\n");
}
